AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Agent API secured with Amazon Cognito

Resources:
  AgentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt AuthUserPool.Arn
            Identity:
              Header: Authorization
      Cors:
        AllowOrigin: "'http://localhost:5173'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"

  AgentApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/app.lambda_handler
      Runtime: python3.13
      Environment:
        Variables:
          AGENTS_TABLE: !Ref AgentsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AgentsTable
      Events:
        ListAgents:
          Type: Api
          Properties:
            Path: /agents
            Method: GET
            RestApiId: !Ref AgentApi
        GetAgent:
          Type: Api
          Properties:
            Path: /agents/{id}
            Method: GET
            RestApiId: !Ref AgentApi
        CreateAgent:
          Type: Api
          Properties:
            Path: /agents
            Method: POST
            RestApiId: !Ref AgentApi
        UpdateAgent:
          Type: Api
          Properties:
            Path: /agents/{id}
            Method: PUT
            RestApiId: !Ref AgentApi
        DeleteAgent:
          Type: Api
          Properties:
            Path: /agents/{id}
            Method: DELETE
            RestApiId: !Ref AgentApi
        RunAgent:
          Type: Api
          Properties:
            Path: /agents/{id}/run
            Method: POST
            RestApiId: !Ref AgentApi

  AuthUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-user-pool'
      AutoVerifiedAttributes:
        - email

  AuthUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref AuthUserPool
      GenerateSecret: false

  AgentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  ApiUrl:
    Description: "API endpoint URL"
    Value: !Sub "https://${AgentApi}.execute-api.${AWS::Region}.amazonaws.com/prod"
  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref AuthUserPool
  UserPoolClientId:
    Description: "User Pool Client ID"
    Value: !Ref AuthUserPoolClient
